Controllers/InquiryController.cs
using Microsoft.AspNetCore.Mvc;
using InquiryManagementApp.Models;
using Microsoft.EntityFrameworkCore;

namespace InquiryManagementApp.Controllers
{
    public class InquiryController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly EmailService _emailService;


        public InquiryController(ApplicationDbContext context, EmailService emailService)
        {
            _context = context;
            _emailService = emailService;
        }

        // GET: Inquiry
        public async Task<IActionResult> IndexAsync()
        {
            return View(await _context.Inquiries.ToListAsync());
        }

        // GET: Inquiry/Create
        public IActionResult Create()
        {
            return View(new Inquiry());
        }

        [HttpPost]
        public IActionResult UpdateReason(int inquiryId, string reason)
        {
            var inquiry = _context.Inquiries.FirstOrDefault(i => i.InquiryId == inquiryId);

            if (inquiry != null)
            {
                inquiry.Reason = reason;
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Reason saved successfully!";
                return RedirectToAction("Details", new { id = inquiryId });
            }
            TempData["ErrorMessage"] = "Unable to find the inquiry.";
            return RedirectToAction("Index", "Admin");
        }

        public IActionResult Details(int id)
        {
            var inquiry = _context.Inquiries.FirstOrDefault(i => i.InquiryId == id);
            if (inquiry == null)
            {
                return NotFound();
            }

            return View(inquiry);
        }

        [HttpGet]
        public async Task<IActionResult> Cancel(int id)
        {
            var student = await _context.Inquiries.FirstOrDefaultAsync(c => c.InquiryId == id);
            if (student != null)
            {
                if (student.IsCancelled)
                {
                    TempData["ErrorMessage"] = "Inquiry already cancelled.";
                    return RedirectToAction("Index", "Home");
                }
            }

            var viewModel = new InquiryCancellationViewModel
            {
                InquiryId = id
            };
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Confirm(int id)
        {
            var student = await _context.Inquiries.FirstOrDefaultAsync(c => c.InquiryId == id);
            if (student != null)
            {
                if (student.IsConfirmed)
                {
                    TempData["ErrorMessage"] = "Inquiry already confirmed.";
                    return RedirectToAction("Index", "Home");
                }
                student.IsConfirmed = true;
                _context.Update(student);

                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Inquiry confirmed successfully.";
                return RedirectToAction("Index", "Home");
            }

            TempData["ErrorMessage"] = "Inquiry not found.";
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cancel(InquiryCancellationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var inquiry = await _context.Inquiries.FindAsync(model.InquiryId);
                if (inquiry != null)
                {
                    inquiry.IsCancelled = true;
                    inquiry.CancellationReason = model.CancellationReason;
                    inquiry.CancellationNotes = model.CancellationNotes;
                    await _context.SaveChangesAsync();

                    var recent = new RecentActivity
                    {
                        Activity = $"Inquiry {inquiry.InquiryId} cancelled",
                        CreatedAt = DateTime.Now
                    };
                    _context.RecentActivities.Add(recent);
                    await _context.SaveChangesAsync();

                    TempData["SuccessMessage"] = "Inquiry canceled successfully.";
                    return RedirectToAction("Index", "Home");
                }

                TempData["ErrorMessage"] = "Inquiry not found.";
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Inquiry inquiry)
        {
            if (ModelState.IsValid)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(inquiry.ContactNumber, @"^[0-9]\d{1,14}$"))
                {
                    TempData["ErrorMessage"] = "Invalid contact number format.";
                    return View(inquiry);
                }

                if (!System.Text.RegularExpressions.Regex.IsMatch(inquiry.EmailAddress, @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"))
                {
                    TempData["ErrorMessage"] = "Invalid email address format.";
                    return View(inquiry);
                }

                var admins = await _context.Accounts.FirstOrDefaultAsync(a => a.Email == inquiry.EmailAddress);
                if (admins != null)
                {
                    TempData["ErrorMessage"] = "Email already exists.";
                    return View(inquiry);
                }
                if (await _context.Inquiries.FirstOrDefaultAsync(a => a.ContactNumber == inquiry.ContactNumber) != null)
                {
                    TempData["ErrorMessage"] = "Contact number is already being used.";
                    return View(inquiry);
                }

                if (await _context.Inquiries.FirstOrDefaultAsync(a => a.EmailAddress == inquiry.EmailAddress) != null
                 || await _context.Students.FirstOrDefaultAsync(a => a.Email == inquiry.EmailAddress) != null
                 || await _context.Accounts.FirstOrDefaultAsync(a => a.Email == inquiry.EmailAddress) != null)
                {
                    TempData["ErrorMessage"] = "Email is already being used.";
                    return View(inquiry);
                }

                if (inquiry.DateOfBirth.AddYears(4) > DateTime.Now)
                {
                    TempData["ErrorMessage"] = "Student must be at least 4 years old.";
                    return View(inquiry);
                }
                if (inquiry.DateOfBirth.AddYears(80) <= DateTime.Now)
                {
                    TempData["ErrorMessage"] = "Invalid year.";
                    return View(inquiry);
                }

                inquiry.StudentName = inquiry.Firstname + " " + (inquiry.Middlename?.First() + "." ?? "") + " " + inquiry.Surname;
                inquiry.DateCreated = DateTime.Now;
                _context.Add(inquiry);
                await _context.SaveChangesAsync();

                string subject = "Inquiry Confirmation";
                string confirmationLink = Url.Action("CreateClick", "Enrollment", new { id = inquiry.InquiryId }, Request.Scheme) ?? "";
                string body = $@"
                    <div style='font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f9ff; padding: 20px;'>
                    <table style='width: 100%; max-width: 600px; margin: auto; background-color: #fff; border: 1px solid #d9e6f2; border-radius: 8px;'>
                        <thead style='background-color: #0056b3; color: #fff;'>
                            <tr>
                                <th style='padding: 15px; text-align: left; display: flex; align-items: center;'>
                                    <img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO9a84kDZORy-tOxHr1uSsYZM4hubrh6AThQ&s' alt='School Logo' style='height: 50px; margin-right: 15px;'>
                                    <div>
                                        <h2 style='margin: 0; font-size: 24px;'>DE ROMAN MONTESSORI SCHOOL</h2>
                                        <p style='margin: 0; font-size: 14px;'>Your gateway to excellence in education</p>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                            <tbody>
                                <tr>
                                    <td style='padding: 20px;'>
                                        <p style='font-size: 16px; color: #0056b3;'>Dear <strong>{inquiry.StudentName}</strong>,</p>
                                        <p style='font-size: 14px;'>Thank you for reaching out to us! Your inquiry has been successfully recorded. We are excited to assist you and will get back to you shortly.</p>
                                        <p style='font-size: 14px;'>If you’re ready to take the next step, you can enroll by clicking the button below:</p>
                                        <div style='text-align: center; margin: 20px 0;'>
                                            <a href='{confirmationLink}' 
                                                style='display: inline-block; padding: 12px 24px; background-color: #0056b3; color: #fff; text-decoration: none; font-size: 16px; border-radius: 5px;'>
                                                Proceed to Enrollment
                                            </a>
                                        </div>
                                        <p style='font-size: 14px;'>If you have any questions or need assistance, feel free to reply to this email or contact us directly:</p>
                                        <ul style='font-size: 14px; color: #333;'>
                                        <li><strong>Email:</strong> <a href='mailto:depedcavite.deromanmontessori@gmail.com' style='color: #0056b3;'>depedcavite.deromanmontessori@gmail.com</a></li>

Views/Shared/_Layout.cshtml
@inject InquiryManagementApp.Service.EnrollmentScheduleService EnrollmentController
@{
    var isEnrollmentActive = EnrollmentController.IsEnrollmentOpen();
    @* var notificationsJson = Context.Session.GetString("Notifications");

    List<Notification> notifications = string.IsNullOrEmpty(notificationsJson)
        ? new List<Notification>()
        : System.Text.Json.JsonSerializer.Deserialize<List<Notification>>(notificationsJson); *@
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        @* * {
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif !important;
        } *@

        * {
            user-select: none !important;
        }

        body {
            font-family: 'Arial', sans-serif;
            @* background-color: #F4F6F9; *@
        @* background: linear-gradient(to right, yellow, blue, blue) !important; *@
        }

        .navbar {
            background-color: #006BFF;
        }

        .navbar a {
            color: #FFFFFF !important;
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 1.6rem;
        }

        .navbar-nav .nav-link {
            font-size: 1rem;
        }

        .hero-section {
            margin-top: 50px;
            @* background-image: url('src/background.jpg'); *@
            background-size: cover;
            background-position: center;
            color: #FFFFFF;
            padding: 80px 0;
            min-height: 80vh;
            position: relative;

            box-shadow: inset 0 -200px 150px rgba(0, 0, 0, 0.4);
        }


        .hero-section h2 {
            font-size: 3rem;
            font-weight: bold;
        }

        .hero-section p {
            font-size: 1.25rem;
            max-width: 700px;
            margin: 0 auto;
        }

        .cta-buttons .btn {
            font-size: 1.2rem;
            padding: 12px 30px;
            margin: 10px;
            border-radius: 30px;
        }

        .cta-buttons .btn-primary {
            background-color: #006BFF;
            border-color: #006BFF;
        }

        .cta-buttons .btn-primary:hover {
            background-color: #08C2FF;
            border-color: #08C2FF;
        }

        .cta-buttons .btn-secondary {
            background-color: #FFF100;
            border-color: #FFF100;
            color: #006BFF;
        }

        .cta-buttons .btn-secondary:hover {
            background-color: #08C2FF;
            border-color: #08C2FF;
            color: #FFFFFF;
        }

        .btn-primary:hover {
            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.3);
            transform: translateY(-3px);
            transition: all 0.2s ease-in-out;
        }

        .programs {
            background-color: #F9F9F9;
            padding: 50px 0;
        }

        .programs h3 {
            font-size: 2rem;
            font-weight: bold;
            margin-bottom: 30px;
        }

        .programs .list-group-item {
            font-size: 1.1rem;
            border: none;
            padding: 10px 15px;
            background-color: #FFFFFF;
        }

        .programs .list-group-item:hover {
            background-color: #F1F1F1;
        }

        .card-deck .card {
            border: none;
            border-radius: 12px;
            box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.1);
        }

        .card-title {
            color: #006BFF;
        }

        .card-body p {
            color: #555555;
        }

        .card-footer {
            text-align: center;
            background-color: #F9F9F9;
        }

        footer {
            background-color: #006BFF;
            color: #FFF100;
            padding: 20px 0;
        }

        footer p {
            font-size: 1rem;
            margin-bottom: 0;
        }
    </style>
</head>

<body class="d-flex flex-column min-vh-100">



<header class="navbar navbar-expand-lg fixed-top" style="background-color: #105FE9FF; color: white;">
    <div class="container">
        <a class="navbar-brand fw-bold text-white" href="@Url.Action("Index", "Home")">
            <img src="~/src/logo.png" alt="Logo"
                style="border-radius: 50%; width: 40px; height: 40px; margin-right: 10px;">
            DE ROMAN MONTESSORI SCHOOL
        </a>
        <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" href="@Url.Action("Index", "Home")">
                        <i class="fas fa-home me-2"></i>Home
                    </a>
                </li>

                @if (Context.Session.GetString("isAdmin") == "1")
                {
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("ManageAccounts", "Admin")">
                            <i class="fas fa-users me-2"></i>Accounts
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("ManageEnrollees", "Admin")">
                            <i class="fas fa-users-cog me-2"></i>Enrollees
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("ManageInquiries", "Admin")">
                            <i class="fas fa-comments me-2"></i>Inquiries
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("ManageTransactions", "Admin")">
                            <i class="fas fa-file-invoice me-2"></i>Transactions
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Logout", "Admin")">
                            <i class="fas fa-sign-out-alt me-2"></i>Logout
                        </a>
                    </li>
                }
                else if (Context.Session.GetString("isAdmin") == "2") {
                    <li class="nav-item dropdown">
                        <a class="nav-link text-white" href="@Url.Action("Notification", "Home")">
                            <i class="fas fa-bell me-2"></i>Notifications
                        </a>
                    </li>
                    @if (!string.IsNullOrEmpty(Context.Session.GetString("GradeLevel")) && 
                    Context.Session.GetString("GradeLevel") == "ELEMENTARY")
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" href="@Url.Action("Assessment", "Home")">
                                <i class="fas fa-file-invoice me-2"></i>Assessment
                            </a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Document", "Home")">
                            <i class="fas fa-file-invoice me-2"></i>Documents
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("PaymentHistory", "Payment")">
                            <i class="fas fa-file-invoice me-2"></i>Payment History
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Logout", "Admin")">
                            <i class="fas fa-sign-out-alt me-2"></i>Logout
                        </a>
                    </li>
                }
                else if (Context.Session.GetString("isAdmin") == "3")
                {
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("ManageInquiries", "Admin")">
                            <i class="fas fa-comments me-2"></i>Inquiries
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Logout", "Admin")">
                            <i class="fas fa-sign-out-alt me-2"></i>Logout
                        </a>
                    </li>
                }
                else
                {
                    
                    
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Login", "Account")">
                            <i class="fas fa-sign-in-alt me-2"></i>Login
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Create", "Inquiry")">
                            <i class="fas fa-question-circle me-2"></i>Create Inquiry
                        </a>
                    </li>
                    @* if (isEnrollmentActive)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" href="@Url.Action("Create", "Enrollment")">
                                <i class="fas fa-user-plus me-2"></i>Enroll
                            </a>
                        </li>
                    } *@
                }
            </ul>
        </div>
    </div>
</header>
    @RenderBody()

    <footer class="text-center bg-primary text-white py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-3">
                    <h5 style="color:#FFF100"><strong>DE ROMAN MONTESSORI SCHOOL</strong></h5>
                    <p>&copy; 2024 All rights reserved.</p>
                </div>

                <div class="col-md-4 mb-3">
                    <h5 style="color:#FFF100"><strong>Contact Information</strong></h5>
                    <p><strong>Location:</strong> Tanza, Philippines</p>
                    <p><strong>Phone:</strong> <a href="tel:+639274044188" class="text-white">0927 404 4188</a></p>
                    <p><strong>Email:</strong> <a href="mailto:depedcavite.deromanmontessori@gmail.com"
                            class="text-white">depedcavite.deromanmontessori@gmail.com</a></p>
                </div>

                <div class="col-md-4 mb-3">
                    <h5 style="color:#FFF100"><strong>Follow Us</strong></h5>
                    <a href="https://www.facebook.com/drmscavite/" target="_blank" class="text-white me-3">
                        <i class="fab fa-facebook-f"></i> Facebook
                    </a>
                    <br>
                    <strong>Opening Hours:</strong> 9:00 AM - 5:00 PM
                </div>
            </div>

            <hr class="my-3" style="border-top: 2px solid #FFF100;">
            <p class="small mb-0">Designed with care by the DE ROMAN MONTESSORI SCHOOL Team</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

<script>
    function showNotification() {
        alert("You have a new notification!");
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $(document).ready(function () {
    @if (TempData["SuccessMessage"] != null)
    {
        <text>
                    Swal.fire({
                        icon: 'success',
                    title: 'Success',
                    text: '@TempData["SuccessMessage"]',
                    showConfirmButton: false,
                    timer: 3000
                                                                                                        });
        </text>
    }

    @if (TempData["ErrorMessage"] != null)
    {
        <text>
                    Swal.fire({
                        icon: 'error',
                    title: 'Error',
                    text: '@TempData["ErrorMessage"]',
                    showConfirmButton: true
                                                                                                        });
        </text>
    }
    });
</script>